    
# Continuous integration with travis
language: r
sudo: required
warnings_are_errors: false

# cache packages to speed up builds
cache: packages

before_install:
  - if [[ "$OSTYPE" != "linux-gnu" ]];
    then sudo tlmgr install index;
    else tlmgr install index;
    fi

addons:
  apt:
    packages:
      - libgdal-dev
      - libproj-dev
      - libudunits2-dev
      
r_packages:
 - covr
 - testthat
 - raster
 - sp 
 - devtools
 - rgeos
 - splancs
 - Matrix
 - stats
 - TMB
 - RcppEigen

coverage:
  status:
    project:
      default:
        threshold: 5%
        target: 80%

after_success:
 - Rscript -e 'library(covr);codecov()'

matrix:
  include:
    - r: release
      r_github_packages: andrewzm/INLA
      os: linux
    - r: devel
      r_github_packages: andrewzm/INLA
      os: linux
    - r: devel
      env: _R_CHECK_FORCE_SUGGESTS_=false
      install: R -e 'install.packages("devtools", dep = TRUE);devtools::install_deps(dep = c("Depends", "Imports"))'

