    
# Continuous integration with travis
language: r
sudo: required

# cache packages to speed up builds
#cache: packages

addons:
  apt:
    packages:
      - libgdal-dev
      - libproj-dev
      
r_packages:
 - covr
 - testthat
 - raster
 - sp 
 - devtools
 - rgeos
 - splancs
 - Matrix
 - stats
 - TMB
 - RcppEigen
 
before_install:
  - mkdir -p ~/.R
  - echo "CXX14FLAGS=-O3 -mtune=native -march=native -Wno-unused-variable -Wno-unused-function  -Wno-macro-redefined" >> ~/.R/Makevars
  - echo "CXX14=g++ -std=c++1y -fPIC" >> ~/.R/Makevars

after_success:
 - Rscript -e 'library(covr);codecov()'


matrix:
  include:
    - r: release
      r_github_packages: andrewzm/INLA

env:
  global:
  - TRAVIS_CXXFLAGS="-Wall -Wextra -pedantic -Werror"
  - R_REMOTES_NO_ERRORS_FROM_WARNINGS=true
