    
# Continuous integration with travis
language: r
sudo: required
warnings_are_errors: false

# cache packages to speed up builds
cache: 
  packages: true

before_install:
  - tlmgr install index

addons:
  apt:
    packages:
      - libgdal-dev
      - libproj-dev
      - libudunits2-dev
      
r_packages:
 - covr
 - testthat
 - raster
 - sp 
 - devtools
 - rgeos
 - splancs
 - Matrix
 - stats
 - TMB
 - RcppEigen
 
after_success:
 - Rscript -e 'library(covr);codecov()'

matrix:
  include:
    - r: release
      r_github_packages: andrewzm/INLA
    - r: devel
      r_github_packages: andrewzm/INLA
    - r: devel
      env: _R_CHECK_FORCE_SUGGESTS_=false
      install: R -e 'install.packages("devtools", dep = TRUE);devtools::install_deps(dep = c("Depends", "Imports"));install.packages("SpatialEpi")'
