    
# Continuous integration with travis
language: r
sudo: required



# cache packages to speed up builds
#cache: packages

addons:
  apt:
    packages:
      - libgdal-dev
      - libproj-dev
      
r_packages:
 - covr
 - testthat
 - raster
 - sp 
 - devtools
 - rgeos
 - splancs
 - Matrix
 - stats
 - TMB
 - RcppEigen

after_success:
 - Rscript -e 'library(covr);codecov()'


matrix:
  include:
    - r: release
      r_github_packages: andrewzm/INLA
